import os
# IN DEVELOPMENT
def generate_su2_cfg():
    print("--- SU2 Configuration File Generator ---")
    print("Press [Enter] to accept the default value shown in brackets.\n")

    # Dictionary of keys and their default values (from your provided cfg)
    config = {
        "SOLVER": "INC_NAVIER_STOKES",
        "MATH_PROBLEM": "DIRECT",
        "RESTART_SOL": "NO",
        "TIME_DOMAIN": "YES",
        "TIME_MARCHING": "DUAL_TIME_STEPPING-2ND_ORDER",
        "TIME_STEP": "0.0001",
        "TIME_ITER": "1000",
        "INNER_ITER": "50",
        "INC_DENSITY_INIT": "1.225",
        "INC_VELOCITY_INIT": "( 27.78, 0.0, 0.0 )",
        "REF_LENGTH": "1.0",
        "REF_AREA": "1.0",
        "MESH_FILENAME": "mesh_NACA64-811.su2",
        "MESH_FORMAT": "SU2",
        "VISCOSITY_MODEL": "CONSTANT_VISCOSITY",
        "MU_CONSTANT": "1.789e-05",
    }

    # Interactive loop
    for key, default in config.items():
        user_input = input(f"{key} [{default}]: ").strip()
        if user_input:
            config[key] = user_input

    # File naming
    filename = input("\nEnter name for the output file [config_sim.cfg]: ").strip() or "config_sim.cfg"

    # Constructing the content (preserving your specific structure)
    cfg_content = f"""% --- Generated by Interactive SU2 Script ---
% Solver Type
SOLVER= {config['SOLVER']}
MATH_PROBLEM= {config['MATH_PROBLEM']}
RESTART_SOL= {config['RESTART_SOL']}

% Time Settings
TIME_DOMAIN= {config['TIME_DOMAIN']}
TIME_MARCHING= {config['TIME_MARCHING']}
TIME_STEP= {config['TIME_STEP']}
TIME_ITER= {config['TIME_ITER']}
INNER_ITER= {config['INNER_ITER']}
BC_EVAL_FREQ= 1

% Flow Conditions
INC_DENSITY_INIT= {config['INC_DENSITY_INIT']}
INC_VELOCITY_INIT= {config['INC_VELOCITY_INIT']}
INC_INLET_TYPE= VELOCITY_INLET
INC_OUTLET_TYPE= PRESSURE_OUTLET

% Reference Values
REF_ORIGIN_MOMENT_X= 0.25
REF_ORIGIN_MOMENT_Y= 0.0
REF_ORIGIN_MOMENT_Z= 0.0
REF_LENGTH= {config['REF_LENGTH']}
REF_AREA= {config['REF_AREA']}

% Boundaries
MARKER_EULER= ( airfoil )
MARKER_INLET= ( inlet, 0.0, 27.78, 1.0, 0.0, 0.0 )
MARKER_OUTLET= ( outlet, 0.0 )
MARKER_FAR= ( farfield )
MARKER_PLOTTING= ( airfoil )
MARKER_MONITORING= ( airfoil )

% Numerics
NUM_METHOD_GRAD= GREEN_GAUSS
CFL_NUMBER= 15.0
CFL_ADAPT= NO
LINEAR_SOLVER= FGMRES
LINEAR_SOLVER_PREC= ILU
LINEAR_SOLVER_ERROR= 1E-10
LINEAR_SOLVER_ITER= 10
RK_ALPHA_COEFF= ( 0.66667, 0.66667, 1.000000 )

% Flow Method
CONV_NUM_METHOD_FLOW= FDS
MUSCL_FLOW= YES
SLOPE_LIMITER_FLOW= VENKATAKRISHNAN
VENKAT_LIMITER_COEFF= 0.05
TIME_DISCRE_FLOW= EULER_IMPLICIT

% Convergence
CONV_RESIDUAL_MINVAL= -6
CONV_STARTITER= 10
CONV_CAUCHY_ELEMS= 100
CONV_CAUCHY_EPS= 1E-6

% Input / Output
MESH_FILENAME= {config['MESH_FILENAME']}
MESH_FORMAT= {config['MESH_FORMAT']}
OUTPUT_FILES= ( RESTART, PARAVIEW, PARAVIEW_MULTIBLOCK, SURFACE_PARAVIEW )
OUTPUT_WRT_FREQ= ( 10, 10, 10, 10 )
VOLUME_OUTPUT= ( COORDINATES, SOLUTION, PRIMITIVE, RESIDUAL )
TABULAR_FORMAT= CSV
HISTORY_OUTPUT= ( ITER, RMS_RES, AERO_COEFF )
SCREEN_OUTPUT= ( TIME_ITER, INNER_ITER, RMS_PRESSURE, RMS_VELOCITY-X, LIFT, DRAG )

% Viscosity
VISCOSITY_MODEL= {config['VISCOSITY_MODEL']}
MU_CONSTANT= {config['MU_CONSTANT']}

% File Paths
VOLUME_FILENAME= output/volume/flow
SURFACE_FILENAME= output/surface/surface_flow
RESTART_FILENAME= output/restart/restart_flow
CONV_FILENAME= output/history
SOLUTION_FILENAME= output/solution/solution_flow
"""

    try:
        with open(filename, "w") as f:
            f.write(cfg_content)
        print(f"\n[SUCCESS] Configuration saved to: {os.path.abspath(filename)}")
    except Exception as e:
        print(f"\n[ERROR] Could not save file: {e}")

if __name__ == "__main__":
    generate_su2_cfg()
